version: '3'

services:
    php:
        restart: always
        image: custom-php
        build: ./docker/php
        ports:
            - 3000:80
        volumes:
            - ./app/src:/var/www/html
